- name: ftp-action
  # You may pin to the exact commit or the version.
  # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
  uses: sebastianpopp/ftp-action@v2.0.0
  with:
    # FTP host
    host: n1.skyhosting.org
    # FTP user
    user: filip769.8ea52793
    # FTP password
    password: x
    # Force SSL encryption
    forceSsl: # optional, default is false
    # Local directory
    localDir: # optional, default is .
    # Remote directory
    remoteDir: # optional, default is .
